"""add_credentials_column

Revision ID: 37526ad7af39
Revises: 20250311_analytics
Create Date: 2025-03-17 00:04:20.693907+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37526ad7af39'
down_revision: Union[str, None] = '20250311_analytics'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_api_usage_logs_client_timestamp', table_name='api_usage_logs')
    op.drop_index('ix_api_usage_logs_endpoint', table_name='api_usage_logs')
    op.drop_index('ix_api_usage_logs_log_id', table_name='api_usage_logs')
    op.drop_index('ix_api_usage_logs_timestamp', table_name='api_usage_logs')
    op.drop_table('api_usage_logs')
    op.drop_index('ix_subscription_usage_client_month', table_name='subscription_usage')
    op.drop_index('ix_subscription_usage_usage_id', table_name='subscription_usage')
    op.drop_table('subscription_usage')
    op.drop_index('ix_chat_metrics_client_date', table_name='chat_metrics')
    op.drop_index('ix_chat_metrics_metric_id', table_name='chat_metrics')
    op.drop_table('chat_metrics')
    op.drop_index('ix_knowledge_metrics_client_collection_date', table_name='knowledge_metrics')
    op.drop_index('ix_knowledge_metrics_metric_id', table_name='knowledge_metrics')
    op.drop_table('knowledge_metrics')
    op.drop_index('ix_daily_stats_client_date', table_name='daily_stats')
    op.drop_index('ix_daily_stats_stat_id', table_name='daily_stats')
    op.drop_table('daily_stats')
    op.drop_index('ix_otp_verifications_email', table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.alter_column('integration_syncs', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('integrations', sa.Column('credentials', sa.JSON(), nullable=True))
    op.add_column('integrations', sa.Column('endpoint_url', sa.String(length=255), nullable=True))
    op.alter_column('integrations', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('integrations', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('integrations', 'status_message',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('integrations', 'api_endpoint')
    op.drop_column('integrations', 'auth_token')
    op.drop_column('integrations', 'auth_expiry')
    op.drop_column('integrations', 'api_secret')
    op.drop_column('integrations', 'refresh_token')
    op.drop_column('integrations', 'api_key')
    op.drop_index('vector_embeddings_item_id_idx', table_name='vector_embeddings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('vector_embeddings_item_id_idx', 'vector_embeddings', ['item_id'], unique=False)
    op.add_column('integrations', sa.Column('api_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('integrations', sa.Column('refresh_token', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('integrations', sa.Column('api_secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('integrations', sa.Column('auth_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('integrations', sa.Column('auth_token', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('integrations', sa.Column('api_endpoint', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('integrations', 'status_message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('integrations', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('integrations', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('integrations', 'endpoint_url')
    op.drop_column('integrations', 'credentials')
    op.alter_column('integration_syncs', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_table('otp_verifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('otp', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('verified', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='otp_verifications_pkey')
    )
    op.create_index('ix_otp_verifications_email', 'otp_verifications', ['email'], unique=True)
    op.create_table('daily_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stat_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('date', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('total_sessions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_messages', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_searches', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_users', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('average_response_time_ms', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('knowledge_usage_ratio', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('stats_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], name='daily_stats_client_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='daily_stats_pkey')
    )
    op.create_index('ix_daily_stats_stat_id', 'daily_stats', ['stat_id'], unique=True)
    op.create_index('ix_daily_stats_client_date', 'daily_stats', ['client_id', 'date'], unique=True)
    op.create_table('knowledge_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('metric_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('collection_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('search_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('average_relevance_score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('items_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('document_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], name='knowledge_metrics_client_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collection_id'], ['knowledge_collections.collection_id'], name='knowledge_metrics_collection_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='knowledge_metrics_pkey')
    )
    op.create_index('ix_knowledge_metrics_metric_id', 'knowledge_metrics', ['metric_id'], unique=True)
    op.create_index('ix_knowledge_metrics_client_collection_date', 'knowledge_metrics', ['client_id', 'collection_id', 'date'], unique=True)
    op.create_table('chat_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('metric_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('total_messages', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('average_response_time_ms', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('knowledge_usage_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_satisfaction', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], name='chat_metrics_client_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], name='chat_metrics_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chat_metrics_pkey')
    )
    op.create_index('ix_chat_metrics_metric_id', 'chat_metrics', ['metric_id'], unique=True)
    op.create_index('ix_chat_metrics_client_date', 'chat_metrics', ['client_id', 'date'], unique=True)
    op.create_table('subscription_usage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usage_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('month_year', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('messages_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('messages_limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active_users', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active_users_limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('storage_used_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('storage_limit_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], name='subscription_usage_client_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name='subscription_usage_subscription_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='subscription_usage_pkey')
    )
    op.create_index('ix_subscription_usage_usage_id', 'subscription_usage', ['usage_id'], unique=True)
    op.create_index('ix_subscription_usage_client_month', 'subscription_usage', ['client_id', 'month_year'], unique=True)
    op.create_table('api_usage_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('log_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('endpoint', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], name='api_usage_logs_client_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='api_usage_logs_pkey')
    )
    op.create_index('ix_api_usage_logs_timestamp', 'api_usage_logs', ['timestamp'], unique=False)
    op.create_index('ix_api_usage_logs_log_id', 'api_usage_logs', ['log_id'], unique=True)
    op.create_index('ix_api_usage_logs_endpoint', 'api_usage_logs', ['endpoint'], unique=False)
    op.create_index('ix_api_usage_logs_client_timestamp', 'api_usage_logs', ['client_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###
