"""sync_subscription_columns

Revision ID: ef58e00ac2d3
Revises: 37526ad7af39
Create Date: 2025-03-18 11:27:02.746759+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef58e00ac2d3'
down_revision: Union[str, None] = '37526ad7af39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subscription_usage_usage_id', table_name='subscription_usage')
    op.drop_table('subscription_usage')
    op.drop_index('ix_knowledge_metrics_metric_id', table_name='knowledge_metrics')
    op.drop_table('knowledge_metrics')
    op.drop_index('ix_daily_stats_stat_id', table_name='daily_stats')
    op.drop_table('daily_stats')
    op.drop_index('ix_otp_verifications_email', table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.drop_index('ix_api_usage_logs_log_id', table_name='api_usage_logs')
    op.drop_table('api_usage_logs')
    op.drop_index('ix_notification_preferences_preference_id', table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index('ix_notifications_notification_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_chat_metrics_metric_id', table_name='chat_metrics')
    op.drop_table('chat_metrics')
    op.add_column('subscriptions', sa.Column('payment_method_id', sa.String(length=255), nullable=True))
    op.add_column('subscriptions', sa.Column('auto_renew', sa.Boolean(), nullable=True))
    op.add_column('subscriptions', sa.Column('billing_cycle', sa.String(length=50), nullable=True))
    op.add_column('subscriptions', sa.Column('is_trial', sa.Boolean(), nullable=True))
    op.add_column('subscriptions', sa.Column('trial_ends_at', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('stripe_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'stripe_data')
    op.drop_column('subscriptions', 'trial_ends_at')
    op.drop_column('subscriptions', 'is_trial')
    op.drop_column('subscriptions', 'billing_cycle')
    op.drop_column('subscriptions', 'auto_renew')
    op.drop_column('subscriptions', 'payment_method_id')
    op.create_table('chat_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('metric_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('total_messages', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('average_response_time_ms', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('knowledge_usage_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_satisfaction', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], name='chat_metrics_client_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], name='chat_metrics_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chat_metrics_pkey')
    )
    op.create_index('ix_chat_metrics_metric_id', 'chat_metrics', ['metric_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('notification_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('notification_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], name='notifications_client_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    op.create_index('ix_notifications_notification_id', 'notifications', ['notification_id'], unique=True)
    op.create_table('notification_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('preference_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('email_limit_warnings', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email_subscription_updates', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email_system_updates', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('inapp_limit_warnings', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('inapp_subscription_updates', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('inapp_system_updates', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('push_limit_warnings', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('push_subscription_updates', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('push_system_updates', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('limit_warning_threshold', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('custom_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], name='notification_preferences_client_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='notification_preferences_pkey')
    )
    op.create_index('ix_notification_preferences_preference_id', 'notification_preferences', ['preference_id'], unique=True)
    op.create_table('api_usage_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('log_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('endpoint', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], name='api_usage_logs_client_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='api_usage_logs_pkey')
    )
    op.create_index('ix_api_usage_logs_log_id', 'api_usage_logs', ['log_id'], unique=True)
    op.create_table('otp_verifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('otp', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('verified', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='otp_verifications_pkey')
    )
    op.create_index('ix_otp_verifications_email', 'otp_verifications', ['email'], unique=True)
    op.create_table('daily_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stat_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('date', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('total_sessions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_messages', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_searches', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_users', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('average_response_time_ms', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('knowledge_usage_ratio', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('stats_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], name='daily_stats_client_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='daily_stats_pkey')
    )
    op.create_index('ix_daily_stats_stat_id', 'daily_stats', ['stat_id'], unique=True)
    op.create_table('knowledge_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('metric_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('collection_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('search_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('average_relevance_score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('items_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('document_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], name='knowledge_metrics_client_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collection_id'], ['knowledge_collections.collection_id'], name='knowledge_metrics_collection_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='knowledge_metrics_pkey')
    )
    op.create_index('ix_knowledge_metrics_metric_id', 'knowledge_metrics', ['metric_id'], unique=True)
    op.create_table('subscription_usage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usage_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('month_year', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('messages_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('messages_limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active_users', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active_users_limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('storage_used_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('storage_limit_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], name='subscription_usage_client_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name='subscription_usage_subscription_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='subscription_usage_pkey')
    )
    op.create_index('ix_subscription_usage_usage_id', 'subscription_usage', ['usage_id'], unique=True)
    # ### end Alembic commands ###
